# Generated by Django 3.2.23 on 2024-01-02 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_newpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewPage',
        ),
    ]
