# Generated by Django 3.2.23 on 2024-01-03 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_delete_newpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovaPagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_new_page', models.CharField(max_length=100)),
            ],
        ),
    ]
