# Generated by Django 3.2.23 on 2024-01-03 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_novapagina'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NovaPagina',
        ),
    ]
