# Generated by Django 3.2.23 on 2024-01-12 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_delete_novapagina'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionCopy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('polls.question',),
        ),
    ]
